# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
  # https://docs.vagrantup.com.

  # Every Vagrant development environment requires a box. You can search for
  # boxes at https://vagrantcloud.com/search.
  config.vm.box = "generic/alpine318"
  config.vm.synced_folder "./shared", "/vagrant_shared", create: false

  config.vm.provider "virtualbox" do |vb|
    vb.gui = false      # Display the VirtualBox GUI when booting the machine
    vb.memory = "2048"  # 1024 is not enough
    vb.cpus = 1
  end

  config.vm.define "RobrodriS" do |server|
    server.vm.network "private_network", ip: "192.168.56.110"
    server.vm.hostname = "RobrodriS"

    server.vm.provider "virtualbox" do |vb|
      vb.name = "RobrodriS"
    end

    server.vm.provision "shell", path: "scripts/server.sh"
  end
end
