# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
  config.vm.box = "generic/alpine318"
  config.vm.synced_folder "./shared", "/vagrant_shared", create: true 

  config.vm.provider "virtualbox" do |vb|
    vb.gui = false
    vb.memory = "2048"
    vb.cpus = 1
  end

  config.vm.define "RobrodriS" do |server|
    server.vm.hostname = "RobrodriS"
    server.vm.network "private_network", ip: "192.168.56.110"

    server.vm.provider "virtualbox" do |vb|
      vb.name = "RobrodriS"
    end

    server.vm.provision "shell", path: "scripts/server.sh"
  end

  config.vm.define "RobrodriSW" do |serverWorker|
    serverWorker.vm.hostname = "RobrodriSW"
    serverWorker.vm.network "private_network", ip: "192.168.56.111"

    serverWorker.vm.provider "virtualbox" do |vb|
      vb.name = "RobrodriSW"
    end

    serverWorker.vm.provision "shell", path: "scripts/worker.sh"
  end
end
