Vagrant.configure("2") do |config|
  config.vm.define "lvarela" do |server|
    server.vm.box = "generic/alpine318"

    # Carpeta compartida
    server.vm.synced_folder ".", "/vagrant", type: "virtualbox"
    
    # Recursos
    server.vm.provider "virtualbox" do |vb|
      vb.name = "lvarela"
      vb.memory = 4096
      vb.cpus = 2
    end

    # Red y hostname
    server.vm.hostname = "lvarela"
    server.vm.network "private_network", ip: "192.168.56.110"
  end
end
